---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      #nodeSelector:
      #  app: webgoat
      containers:
        - name: webgoat
          image: webgoat/webgoat
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m      # CPU minimum requis
              memory: 128Mi  # RAM minimum requise
            limits:
              cpu: 200m      # CPU maximum autorisé
              memory: 256Mi  # RAM maximum autorisée  
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat-nodeport
spec:
  selector:
    app: webgoat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
spec:
  selector:
    app: webgoat
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: webgoat.jhous.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webgoat-service
                port:
                  number: 8080
